// Copyright (C) Microsoft Corporation. All rights reserved.
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#define EXECUTION_CONTEXT_REGISTRY_BUILTIN_PROFILE_ROOT_WIN32 \
    L"SYSTEM\\CurrentControlSet\\Services\\NDIS\\Parameters"
#define EXECUTION_CONTEXT_REGISTRY_BUILTIN_PROFILE_ROOT_NT \
    L"\\Registry\\Machine\\SYSTEM\\CurrentControlSet\\Services\\NDIS\\Parameters"
#define EXECUTION_CONTEXT_REGISTRY_BUILTIN_PROFILE_PATH \
    L"Reserved\\ExecutionContextProfiles"

#define EXECUTION_CONTEXT_REGISTRY_CUSTOM_PROFILE_ROOT_WIN32 \
    L"SYSTEM\\CurrentControlSet\\Services\\NDIS\\State"
#define EXECUTION_CONTEXT_REGISTRY_CUSTOM_PROFILE_ROOT_NT \
    L"\\Registry\\Machine\\SYSTEM\\CurrentControlSet\\Services\\NDIS\\State"
#define EXECUTION_CONTEXT_REGISTRY_CUSTOM_PROFILE_PATH \
    L"Reserved\\ExecutionContextProfiles"

#define EXECUTION_CONTEXT_REGISTRY_PROFILE_MAX_NAME_LENGTH 256 // num characters, including trailing null

#define EXECUTION_CONTEXT_REGISTRY_DEFAULTPROFILE_NAME \
    L"DefaultProfile"

#define EXECUTION_CONTEXT_REGISTRY_FLAGS_NAME \
    L"Flags"
#define EXECUTION_CONTEXT_REGISTRY_MAXTIMEATDISPATCH_NAME \
    L"MaxTimeAtDispatch"
#define EXECUTION_CONTEXT_REGISTRY_DPCWATCHDOGTIMERTHRESHOLD_NAME \
    L"DpcWatchdogTimerThreshold"
#define EXECUTION_CONTEXT_REGISTRY_MAXPACKETSSENDATPASSIVE_NAME \
    L"MaxPacketsSendAtPassive"
#define EXECUTION_CONTEXT_REGISTRY_MAXPACKETSSENDCOMPELTEATPASSIVE_NAME \
    L"MaxPacketsSendCompleteAtPassive"
#define EXECUTION_CONTEXT_REGISTRY_MAXPACKETSRECEIVEATPASSIVE_NAME \
    L"MaxPacketsReceiveAtPassive"
#define EXECUTION_CONTEXT_REGISTRY_MAXPACKETSRECEIVECOMPLETEATPASSIVE_NAME \
    L"MaxPacketsReceiveCompleteAtPassive"
#define EXECUTION_CONTEXT_REGISTRY_MAXPACKETSSENDATDISPATCH_NAME \
    L"MaxPacketsSendAtDispatch"
#define EXECUTION_CONTEXT_REGISTRY_MAXPACKETSSENDCOMPELTEATDISPATCH_NAME \
    L"MaxPacketsSendCompleteAtDispatch"
#define EXECUTION_CONTEXT_REGISTRY_MAXPACKETSRECEIVEATDISPATCH_NAME \
    L"MaxPacketsReceiveAtDispatch"
#define EXECUTION_CONTEXT_REGISTRY_MAXPACKETSRECEIVECOMPLETEATDISPATCH_NAME \
    L"MaxPacketsReceiveCompleteAtDispatch"

#define EXECUTION_CONTEXT_ALL_REGISTRY_VALUES \
    ECVALUE(REG_DWORD, EXECUTION_CONTEXT_REGISTRY_FLAGS_NAME) \
    ECVALUE(REG_DWORD, EXECUTION_CONTEXT_REGISTRY_MAXTIMEATDISPATCH_NAME) \
    ECVALUE(REG_DWORD, EXECUTION_CONTEXT_REGISTRY_DPCWATCHDOGTIMERTHRESHOLD_NAME) \
    ECVALUE(REG_DWORD, EXECUTION_CONTEXT_REGISTRY_MAXPACKETSSENDATPASSIVE_NAME) \
    ECVALUE(REG_DWORD, EXECUTION_CONTEXT_REGISTRY_MAXPACKETSSENDCOMPELTEATPASSIVE_NAME) \
    ECVALUE(REG_DWORD, EXECUTION_CONTEXT_REGISTRY_MAXPACKETSRECEIVEATPASSIVE_NAME) \
    ECVALUE(REG_DWORD, EXECUTION_CONTEXT_REGISTRY_MAXPACKETSRECEIVECOMPLETEATPASSIVE_NAME) \
    ECVALUE(REG_DWORD, EXECUTION_CONTEXT_REGISTRY_MAXPACKETSSENDATDISPATCH_NAME) \
    ECVALUE(REG_DWORD, EXECUTION_CONTEXT_REGISTRY_MAXPACKETSSENDCOMPELTEATDISPATCH_NAME) \
    ECVALUE(REG_DWORD, EXECUTION_CONTEXT_REGISTRY_MAXPACKETSRECEIVEATDISPATCH_NAME) \
    ECVALUE(REG_DWORD, EXECUTION_CONTEXT_REGISTRY_MAXPACKETSRECEIVECOMPLETEATDISPATCH_NAME) \

#ifdef __cplusplus
}
#endif

